language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
  - phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
